{
 "title": "Greetings",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Personal Greetings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "things_sent_greetings_personal_total",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "things_sent_greetings_personal_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Greetings from last 10 minutes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(things_sent_greetings_total[10m])"
    }
   ]
  },
  {
   "title": "Total greetings",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "things_sent_greetings_total" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(things_sent_greetings_personal_total[10m])"
    }
   ]
  }
 ]
}