{
 "title": "Sleep",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Average sleep duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "things_sleep_requested_seconds_sum / things_sleep_requested_seconds_count"
    }
   ]
  },
  {
   "title": "Increase per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(things_sleep_requested_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(things_sleep_requested_seconds_count[1m])"
    }
   ]
  }
 ]
}