############################################################################
# Copyright 2019, 2021, Staffbase GmbH and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################

global:

  # How frequently to scrape targets by default.
  scrape_interval: 5s

  # How long until a scrape request times out.
  scrape_timeout: 2s

  # How frequently to evaluate rules.
  evaluation_interval: 1m

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:


# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
#  [ - <filepath_glob> ... ]

# A list of scrape configurations.
scrape_configs:
  #[ - <scrape_config> ... ]
  - job_name: 'things'
    scrape_interval: 2s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.4:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
